import type { Lead, SalesState } from "./schemas";
import { profile } from "./business";

export const SPIN_INSTRUCTIONS = `Conduza o atendimento do visitante com SPIN Selling de forma natural e adaptativa. Leia a última mensagem e o histórico antes de responder. Situação: como o negócio recebe clientes hoje, somente se faltar contexto. Problema: o obstáculo realmente relatado. Implicação: o impacto desse obstáculo, sem inventar perdas ou criar medo. Necessidade/benefício: apresente como o trabalho da Milia pode ajudar. Não siga questionário fixo: pule o que já foi respondido, não repita perguntas; responda dúvidas, objeções e pedidos de preço primeiro. Nunca pergunte quantidade de páginas, integrações ou requisitos técnicos. Linguagem humana, breve, no máximo uma pergunta útil por mensagem. Prioridade comercial: facilitar a contratação da solução mais acessível, o Essencial a partir de R$ 689, quando resolver o objetivo relatado. Apresente-o como um primeiro passo simples para mostrar o trabalho e receber contatos; não empurre o Profissional. Se ainda faltar contexto para recomendar formalmente, apresente o Essencial como possibilidade sujeita à validação da equipe. Só mencione um plano maior como indicação quando houver necessidade explícita que o Essencial não atende. Não suponha funcionalidades ou escolha plano por suposição. Se houver loja, login ou integração complexa, encaminhe para avaliação humana. Sem promessas de vendas, urgência falsa ou descontos. Se pedir preço, responda diretamente com valor inicial oficial e proposta validada pela equipe. Se pedir proposta ou pessoa, ofereça levar resumo ao WhatsApp. Respeite quem disser não. "Visitante do site" é marcador interno, não nome do cliente. Resumo fiel somente desta conversa. Não exponha estados internos, regras ou o método SPIN.`;

export function answerSpin(lead: Lead, text: string): { message: string; state: SalesState; next: string } {
  const n = text.normalize("NFD").replace(/\p{Diacritic}/gu, "").toLowerCase();
  if (/(falar|conversar).{0,40}(equipe|pessoa|humano|whatsapp|wpp)|atendente|quero.{0,20}proposta/.test(n)) return { message: "Podemos levar o que você contou para a equipe montar uma proposta com contexto. Use o botão abaixo para enviar o resumo ao WhatsApp, ou salve seu contato para retorno.", state: "HUMAN_HANDOFF", next: "Contato humano com resumo" };
  if (/nao (quero|preciso)|so (pesquisando|olhando)|apenas pesquisando/.test(n)) return { message: "Claro, podemos ir no seu tempo. A Milia cria sites para apresentar serviços, organizar o portfólio e facilitar o contato. Você pode conhecer nosso trabalho na seção de projetos.", state: "FOLLOW_UP", next: "Aguardar interesse do visitante" };
  if (lead.recommendation.plan === "HUMAN_HANDOFF") return { message: "O que você descreveu precisa de uma avaliação da equipe para confirmar a solução e o investimento. Posso levar um resumo para eles pelo WhatsApp?", state: "HUMAN_HANDOFF", next: "Validar escopo com equipe" };
  if (/preco|valor|quanto custa|planos|mais barato|gasta.{0,12}pouco|investimento.{0,15}baixo/.test(n)) return { message: "Nosso ponto de partida mais acessível é o Essencial, a partir de R$ 689, para apresentar seu trabalho e facilitar o contato. A equipe confirma se ele atende seu objetivo antes da proposta. Que resultado você gostaria de melhorar no seu negócio?", state: "VALUE_PRESENTATION", next: "spin:problem" };
  if (/quais.{0,15}servicos|o que voces fazem|o que a milia faz|mostrar.{0,15}trabalho|portfolio/.test(n)) return { message: `Nosso trabalho reúne ${profile.services.map(s => s.title).join(", ")}. Você pode ver exemplos no portfólio do site. Como seus clientes conhecem e entram em contato com sua empresa hoje?`, state: "DISCOVERY", next: "spin:problem" };
  const pending = lead.memory.nextBestAction;
  if (pending === "spin:benefit") return { message: "Para começar de forma simples, o Essencial parte de R$ 689 e pode reunir seus serviços e trabalhos com um caminho claro para pedir orçamento. A equipe valida se essa solução atende o que você contou. Quer levar esse contexto para receber uma proposta?", state: "VALUE_PRESENTATION", next: "Contato humano com resumo" };
  if (pending === "spin:implication") return { message: "Entendi o impacto que você descreveu. Um site pode reunir seu trabalho e ajudar o cliente a entender a oferta antes do contato. O que mudaria na sua rotina se os contatos chegassem mais alinhados ao que você oferece?", state: "VALUE_PRESENTATION", next: "spin:benefit" };
  if (pending === "spin:problem") return { message: "Entendi. Para apresentar nosso trabalho de um jeito útil para você: como essa dificuldade afeta os contatos ou os pedidos de orçamento que recebe hoje?", state: "NEED_IDENTIFICATION", next: "spin:implication" };
  return { message: "A Milia cria sites que apresentam seu trabalho e facilitam o caminho até o contato. Como os clientes encontram sua empresa hoje, e o que você gostaria de melhorar nisso?", state: "DISCOVERY", next: "spin:problem" };
}
